{
 "title": "ASMPAT-Oracle",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Rate", "label": "Rate", "query": "5m,10m,15m,30m,1h" },
   { "name": "sql_id", "label": "SQL ID", "query": "label_values(sql_id)" }
  ]
 },
 "panels": [
  {
   "title": "ASMP AT Application queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Provisioning Activities by State",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_provisioning_activity_state_value{job=\"asmpat_oracle\",state=\"A\"}",
       "legendFormat": "Active Activities"
      },
      {
       "expr": "oracledb_asmpat_provisioning_activity_state_value{job=\"asmpat_oracle\",state=\"F\"}",
       "legendFormat": "Failed Activities"
      },
      {
       "expr": "oracledb_asmpat_provisioning_activity_state_value{job=\"asmpat_oracle\",state=\"R\"}",
       "legendFormat": "Retry Activities"
      }
     ]
    },
    {
     "title": "Provisioning Transactions by State",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_provisioning_transactions_state_value{job=\"asmpat_oracle\",state=\"A\"}",
       "legendFormat": "Active Transactions"
      },
      {
       "expr": "oracledb_asmpat_provisioning_transactions_state_value{job=\"asmpat_oracle\",state=\"F\"}",
       "legendFormat": "Failed Transactions"
      },
      {
       "expr": "oracledb_asmpat_provisioning_transactions_state_value{job=\"asmpat_oracle\",state=\"W\"}",
       "legendFormat": "Waiting Transactions"
      }
     ]
    },
    {
     "title": "BANAdmin permissions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_ban_admin_permissions_value{job=\"asmpat_oracle\"}",
       "legendFormat": "BANAdmin permissions"
      }
     ]
    },
    {
     "title": "msisdn.a1.net user count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_user_count_by_type_value{job=\"asmpat_oracle\",subscriber_type=\"31\"}",
       "legendFormat": "msisdn.a1.net"
      }
     ]
    },
    {
     "title": "a1.net user count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_user_count_by_type_value{job=\"asmpat_oracle\",subscriber_type=\"33\"}",
       "legendFormat": "a1.net"
      }
     ]
    },
    {
     "title": "account.a1.net user count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_user_count_by_type_value{job=\"asmpat_oracle\",subscriber_type=\"32\"}",
       "legendFormat": "account.a1.net"
      }
     ]
    }
   ]
  },
  {
   "title": "Oracle Default",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "asmpat_process_count_gauge",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "oracledb_asmpat_process_count{job=\"asmpat_oracle\"}",
       "legendFormat": "asmpat_process_count"
      }
     ]
    },
    {
     "title": "asmpat_process_count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_process_count{job=\"asmpat_oracle\"}",
       "legendFormat": "asmpat_process_count"
      }
     ]
    },
    {
     "title": "asmpat_sessions_value",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_sessions_value{job=\"asmpat_oracle\"}",
       "legendFormat": "session_value={{status}} {{type}}"
      }
     ]
    },
    {
     "title": "asmpat_sessions_per_user",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_sessions_per_user_value{job=\"asmpat_oracle\",username=\"STAGE_MASTER\"}",
       "legendFormat": "{{status}} {{username}}"
      },
      {
       "expr": "oracledb_asmpat_sessions_per_user_value{job=\"asmpat_oracle\",username=\"STAGE_USER\"}",
       "legendFormat": "{{status}} {{username}}"
      }
     ]
    },
    {
     "title": "ASMPAT-LARGE_DATA",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"LARGE_DATA\"}",
       "legendFormat": "size {{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_bytes{job=\"asmpat_oracle\",tablespace=\"LARGE_DATA\"}",
       "legendFormat": "used {{tablespace}}"
      }
     ]
    },
    {
     "title": "ASMPAT-SMALL_DATA",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"SMALL_DATA\"}",
       "legendFormat": "size {{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_bytes{job=\"asmpat_oracle\",tablespace=\"SMALL_DATA\"}",
       "legendFormat": "used {{tablespace}}"
      }
     ]
    },
    {
     "title": "ASMPAT-LARGE_INDEX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"LARGE_INDEX\"}",
       "legendFormat": "size {{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_bytes{job=\"asmpat_oracle\",tablespace=\"LARGE_INDEX\"}",
       "legendFormat": "used {{tablespace}}"
      }
     ]
    },
    {
     "title": "ASMPAT-SMALL_INDEX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"SMALL_INDEX\"}",
       "legendFormat": "size {{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_bytes{job=\"asmpat_oracle\",tablespace=\"SMALL_INDEX\"}",
       "legendFormat": "used {{tablespace}}"
      }
     ]
    },
    {
     "title": "ASMPAT-TEMP",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"TEMP\"}",
       "legendFormat": "size {{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_bytes{job=\"asmpat_oracle\",tablespace=\"TEMP\"}",
       "legendFormat": "used {{tablespace}}"
      }
     ]
    },
    {
     "title": "ASMPAT-UNDOTBS1",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"UNDOTBS1\"}",
       "legendFormat": "size {{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_bytes{job=\"asmpat_oracle\",tablespace=\"UNDOTBS1\"}",
       "legendFormat": "used {{tablespace}}"
      }
     ]
    },
    {
     "title": "asmpat_tablespaces_usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"LARGE_DATA\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"LARGE_INDEX\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"SMALL_DATA\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"SMALL_INDEX\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"TEMP\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_max_bytes{job=\"asmpat_oracle\",tablespace=\"UNDOTBS1\"}",
       "legendFormat": "{{tablespace}}"
      }
     ]
    },
    {
     "title": "asmpat_tablespaces_free",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_tablespace_free{job=\"asmpat_oracle\",tablespace=\"LARGE_DATA\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_free{job=\"asmpat_oracle\",tablespace=\"LARGE_INDEX\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_free{job=\"asmpat_oracle\",tablespace=\"SMALL_DATA\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_free{job=\"asmpat_oracle\",tablespace=\"SMALL_INDEX\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_free{job=\"asmpat_oracle\",tablespace=\"TEMP\"}",
       "legendFormat": "{{tablespace}}"
      },
      {
       "expr": "oracledb_asmpat_tablespace_free{job=\"asmpat_oracle\",tablespace=\"UNDOTBS1\"}",
       "legendFormat": "{{tablespace}}"
      }
     ]
    },
    {
     "title": "transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_resource_current_utilization{job=\"asmpat_oracle\",resource_name=\"transactions\"}",
       "legendFormat": "transactions"
      }
     ]
    },
    {
     "title": "transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_resource_current_utilization{job=\"asmpat_oracle\",resource_name=\"temporary_table_locks\"}",
       "legendFormat": "table locks"
      }
     ]
    },
    {
     "title": "user_rollbacks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_activity_user_rollbacks{job=\"asmpat_oracle\"}",
       "legendFormat": "user_rollbacks"
      }
     ]
    },
    {
     "title": "user_commits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_activity_user_commits{job=\"asmpat_oracle\"}",
       "legendFormat": "user_rollbacks"
      }
     ]
    },
    {
     "title": "user_execute_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_activity_execute_count{job=\"asmpat_oracle\"}",
       "legendFormat": "execute_count"
      }
     ]
    },
    {
     "title": "parse_count_total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_activity_parse_count_total{job=\"asmpat_oracle\"}",
       "legendFormat": "parse_count_total"
      }
     ]
    },
    {
     "title": "locks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_resource_current_utilization{job=\"asmpat_oracle\",resource_name=\"enqueue_locks\"}",
       "legendFormat": "enqueue_locks"
      },
      {
       "expr": "oracledb_asmpat_resource_current_utilization{job=\"asmpat_oracle\",resource_name=\"dml_locks\"}",
       "legendFormat": "dml_locks"
      },
      {
       "expr": "oracledb_asmpat_resource_current_utilization{job=\"asmpat_oracle\",resource_name=\"sort_segment_locks\"}",
       "legendFormat": "sort_segment_locks"
      }
     ]
    },
    {
     "title": "server_resources",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_asmpat_resource_current_utilization{job=\"asmpat_oracle\",resource_name=\"parallel_max_servers\"}",
       "legendFormat": "parallel_max_servers"
      },
      {
       "expr": "oracledb_asmpat_resource_current_utilization{job=\"asmpat_oracle\",resource_name=\"max_shared_servers\"}",
       "legendFormat": "max_shared_servers"
      }
     ]
    }
   ]
  },
  {
   "title": "Top 10 Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_executions[$Rate]))",
       "legendFormat": "Number of executions"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_disk_reads[$Rate]))",
       "legendFormat": "Number of disk reads"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_sharable_mem[$Rate]))"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_cpu_time[$Rate]))"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_elapsed_time[$Rate]))"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_avg_elapsed[$Rate]))"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_avg_cpu[$Rate]))"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_disk_reads[$Rate])) by (sql_id, sql_fulltext, parsing_schema_name)"
      },
      {
       "expr": "sum(increase(oracledb_queriesPerformance_sharable_mem[$Rate])) by (sql_id, sql_fulltext, parsing_schema_name)"
      },
      {
       "expr": "sum(increase(oracledb_queriesPerformance_cpu_time[$Rate])) by (sql_id, sql_fulltext, parsing_schema_name)"
      },
      {
       "expr": "sum(increase(oracledb_queriesPerformance_executions[$Rate])) by (sql_id, sql_fulltext, parsing_schema_name)"
      },
      {
       "expr": "sum(increase(oracledb_queriesPerformance_elapsed_time[$Rate])) by (sql_id, sql_fulltext, parsing_schema_name)"
      },
      {
       "expr": "sum(increase(oracledb_queriesPerformance_avg_elapsed[$Rate])) by (sql_id, sql_fulltext, parsing_schema_name)"
      },
      {
       "expr": "sum(increase(oracledb_queriesPerformance_avg_cpu[$Rate])) by (sql_id, sql_fulltext, parsing_schema_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Performance: ID - $sql_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average elapsed time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_avg_elapsed{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
      }
     ]
    },
    {
     "title": "Average CPU time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_avg_cpu{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
      }
     ]
    },
    {
     "title": "Number of executions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_executions{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
      }
     ]
    },
    {
     "title": "Number of disk reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_disk_reads{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
      }
     ]
    },
    {
     "title": "Amount of shared memory used by the child cursor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_sharable_mem{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
      }
     ]
    },
    {
     "title": "CPU time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_cpu_time{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
      }
     ]
    },
    {
     "title": "Elapsed time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oracledb_queriesPerformance_elapsed_time{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
      }
     ]
    }
   ]
  }
 ]
}