{
 "title": "Oracle Query Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sql_id", "label": "SQL ID", "query": "label_values(sql_id)" },
   { "name": "Rate", "label": "Rate", "query": "5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Average elapsed time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracledb_queriesPerformance_avg_elapsed{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
    }
   ]
  },
  {
   "title": "Average CPU time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracledb_queriesPerformance_avg_cpu{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
    }
   ]
  },
  {
   "title": "Number of executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracledb_queriesPerformance_executions{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
    }
   ]
  },
  {
   "title": "Number of disk reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracledb_queriesPerformance_disk_reads{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
    }
   ]
  },
  {
   "title": "Amount of shared memory used by the child cursor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracledb_queriesPerformance_sharable_mem{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracledb_queriesPerformance_cpu_time{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
    }
   ]
  },
  {
   "title": "Elapsed time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracledb_queriesPerformance_elapsed_time{sql_id=\"$sql_id\"}[$Rate])) by (sql_id)"
    }
   ]
  }
 ]
}